#ifndef APP_APRS_H
#define APP_APRS_H

#define APRS_CALL_LENGTH 6u
#define APRS_POSITION_OFFSET 7u
#define APRS_POSITION_LENGTH 18u
#define APRS_SUFFIX_LENGTH 3u
#define APRS_EDIT_LENGTH (APRS_POSITION_OFFSET + APRS_POSITION_LENGTH + APRS_SUFFIX_LENGTH)
#define APRS_MESSAGE_TEMPLATE "BA7ODY 2307.75N/11315.86E>hi"

void APRS_Transmit(const char *position);

#endif
